version: "3.3"
services:
  app:
    build: ./FlaskApp
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: root
      MYSQL_DATABASE_DB: Bucketlist
      MYSQL_DATABASE_HOST: db

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro